services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face_sync
    network_mode: "host"
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - REDIS_HOST=127.0.0.1
      - PORT=8000
    volumes:
      - ./.env:/app/.env
      - ./version.json:/app/version.json
      - ./storage:/storage
      - flag_data:/app/flag
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      stream:
        condition: service_started
    restart: always

  stream:
    image: bluenviron/mediamtx:latest
    container_name: media_stream
    network_mode: "host"
    environment:
      - MTX_API=yes
      - MTX_APIADDRESS=127.0.0.1:9997
      - MTX_WEBRTC=yes
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    network_mode: "host"
    environment:
      - POSTGRES_USER=facesync
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=facesync_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U facesync -d facesync_db"]
      interval: 2s
      timeout: 2s
      retries: 10
    restart: always

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_stream
    network_mode: "host"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
  flag_data:
